#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: kenzo
#=================================================

name: Build release for immortalwrt 25.12

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
        branch:
          type: choice
          description: 编译版本
          options: 
          - "openwrt-25.12"
          - "openwrt-24.10"
          - "openwrt-23.05"
        is-mini:
          type: boolean
          description: "最小化编译，只为缓存工具链节省编译时间"

 
env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: ${{ inputs.branch }}
  IS_MINI: ${{ inputs.is-mini }}
  CACHE_TOOLCHAIN: true
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 
  TZ: Asia/Shanghai
    
jobs:
  build:
    runs-on: ubuntu-latest 

    name: Build ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(format('["{0}"]', inputs.branch)) }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: 下载编译所需的依赖 (Install the software packages required for compilation)
      run: |
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)' 

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        # sudo -E apt-get -qq update
        # sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache llvm clang cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev rename
        # sudo -E apt-get -qq autoremove --purge
        # sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"

    - name: Free up disk space
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p -m 777 /mnt/openwrt
        ln -sf /mnt/openwrt openwrt
        
    - name: Get current date
      id: date
      run: |
        echo "date=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV
        echo "date2=$(date +'%m/%d %Y')" >> $GITHUB_ENV
        echo "date3=$(date +'%m.%d')" >> $GITHUB_ENV
        echo "DOCKERTAG=${{ secrets.DOCKER_ID }}/openwrt-6p:latest" >> $GITHUB_ENV
        VERSION="$(echo "${{github.event.action}}" | grep -Eo " [0-9.]+" | sed -e 's/ //')" || true
        [ "$VERSION" ] && echo "VERSION=$VERSION" >> $GITHUB_ENV || echo "VERSION=$(date +'%m.%d')" >> $GITHUB_ENV     

   

    - name: Clone source code
      env: 
        TZ: Asia/Shanghai        
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV
        VERSION_INFO=$(git show -s --date=short --format="作者: %an<br/>时间: %cd<br/>内容: %s<br/>hash: %H")
        echo "VERSION_INFO=$VERSION_INFO" >> $GITHUB_ENV
        SOURCE_REPO="$(echo $REPO_URL | awk -F '/' '{print $(NF)}')"
        echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
        SOURCE_AUTHOR="$(echo $REPO_URL | awk -F '/' '{print $4}')"
        echo "SOURCE_AUTHOR=$SOURCE_AUTHOR" >> $GITHUB_ENV
      
    - name: Free up disk space
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p -m 777 /mnt/openwrt/dl /mnt/openwrt/bin /mnt/openwrt/staging_dir
        ln -sf /mnt/openwrt/dl openwrt/dl
        ln -sf /mnt/openwrt/bin openwrt/bin
        ln -sf /mnt/openwrt/staging_dir openwrt/staging_dir
        
    - name: Cache Toolchain(缓存工具链)
      if: env.CACHE_TOOLCHAIN == 'true'
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: true
        mixkey: ${{ env.SOURCE_REPO }}-${{ env.REPO_BRANCH }}-${{ env.SOURCE_AUTHOR }}-x86
        prefix: ${{ env.OPENWRT_PATH }}

    - name: Update feeds
      working-directory: ./openwrt
      if: env.IS_MINI == 'true'
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    
    - name: Defconfig ${{matrix.target}} mini
      working-directory: ./openwrt
      if: env.IS_MINI == 'true'
      env:
        CONFIG_FILE: x86_64/immortalwrt.mini.config
      run: |
        cp -f $GITHUB_WORKSPACE/$CONFIG_FILE .config
        make defconfig
      
    - name: Defconfig ${{matrix.target}}
      if: env.IS_MINI == 'false'
      env:
        CONFIG_FILE: x86_64/immortalwrt25.config
        DIY_P1_SH: diy-part1.sh
        DIY_P2_SH: diy-immortalwrt.sh
        MRG_ADD_SH: x86_64/x86_64.sh
      run: |
        chmod +x $DIY_P2_SH
        chmod +x $MRG_ADD_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH
        $GITHUB_WORKSPACE/$MRG_ADD_SH
        cp -f $GITHUB_WORKSPACE/$CONFIG_FILE .config
        make defconfig
        
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec rm -f {} \;

    - name: Check space usage
      run: |
        shopt -s extglob
        cd openwrt
        if [[ -f staging_dir/*${{ env.MTARGET }}*/bin ]]; then
            rm -rf staging_dir/!(*${{ env.MTARGET }}*|host|hostpkg) build_dir/!(*${{ env.MTARGET }}*|host|hostpkg)
        fi
        df -hT

    - name: Check server performance
      run: |
        echo "警告⚠"
        echo "若分配的服务器性能不足，务必及时取消，重新运行！"
        echo "已知编译成功CPU型号：8370C,8171M"
        echo "已知性能不足CPU型号：8272CL"
        echo -e "-------------- ------------CPU信息------------------------------------------\n"
        echo "CPU物理数量:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
        echo -e "CPU核心及版本信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo "-------------------------------内存信息-------------------------------------------"
        echo "已安装内存详细信息："
        sudo lshw -short -C memory | grep GiB
        echo -e "\n"
        echo "-----------------------------硬盘信息---------------------------------------------"
        echo -e  "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l) \n"
        echo "硬盘详情："
        df -Th 

    - name: Compile tool chain
      if: env.IS_MINI == 'true'
      id: toolchain
      working-directory: ./openwrt
      run: |
        make tools/install -j1
        #make toolchain/install -j$(nproc) V=s  
        make -j$(($(nproc)+1)) || make -j1 V=s

    - name: Compile the firmware
      if: env.IS_MINI == 'false'
      id: compile
      working-directory: ./openwrt
      run: |
        echo -e "$(($(nproc)+1)) thread compile"
        make -j$(($(nproc)+1)) || make -j1 V=s      
        echo "status=success" >> "$GITHUB_OUTPUT"

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true' && env.IS_MINI == 'false'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: Organize files
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled() && env.IS_MINI == 'false'
      run: |
        tar -zcvf AllPackages.tar.gz openwrt/bin/packages
        mv AllPackages.tar.gz openwrt/bin/targets/*/*
        cd openwrt/bin/targets/*/*
        tar -zcvf Packages.tar.gz packages
        rm -rf packages config.buildinfo feeds.buildinfo sha256sums version.buildinfo *.manifest Packages.tar.gz
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> "$GITHUB_OUTPUT"

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled() && env.IS_MINI == 'false'
      with:
        name: ${{ env.date3 }} _${{matrix.target}}
        path: ${{ env.FIRMWARE }}
        
    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled() && env.IS_MINI == 'false'
      run: |
        echo -e "${{ env.date }}_${{matrix.target}}\n" >> release.txt
        touch release.txt
        [ $IS_MINI = true ] && echo "mini编译只为缓存工具链,加速编译时间" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware to release
      uses: softprops/action-gh-release@master
      if: steps.organize.outputs.status == 'success' && !cancelled() && env.IS_MINI == 'false'
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
      with:
        files: "${{ env.FIRMWARE }}/*"
        name: ${{matrix.target}} ${{ env.date2 }} ${{ env.IS_MINI == 'true' && ' mini' || 'release' }}
        tag_name: ${{matrix.target}}_${{ env.date }}_${{ env.IS_MINI == 'true' && ' mini' || 'release' }}
        body_path: release.txt

    # - name: Remove old Releases
    #   uses: dev-drprasad/delete-older-releases@master
    #   if: env.UPLOAD_RELEASE == 'true' && !cancelled()
    #   with:
    #     keep_latest: 6
    #     delete_tags: true
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}

  trigger:
    runs-on: ubuntu-latest
    needs: build 
    if: github.event.inputs.is-mini == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: trigger
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run immortalwrt-25.yml -f branch="openwrt-25.12" is-mini="false"

        



        
