name: test trigger self 

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
        finish:
          type: boolean
          description: "是否结束工作流"

env:
  FINISH: ${{ inputs.finish }}

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: 'test'
        run: |
         echo "hello"
  
  trigger:
    runs-on: ubuntu-latest
    needs: build 
    if: github.event.inputs.finish == 'false'

    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: trigger
        uses: './github/workflows/test.yml'
        with:
          finish: true

